### PR TITLE
Progress assertions

### PR DESCRIPTION
**Pull request by venkatesh-sivaraman**
Adds support for progress assertions.

* `User` (the road document) now stores progress assertions, and also passes through the old progress overrides for backwards compatibility.
* `CourseThumbnailCell` has new methods to respond to "Substitute" and "Ignore" actions on the popup menu, and has styling changes when a progress assertion is active.
* `RequirementsListViewController` responds to these actions by showing a new `CourseMultiSelectViewController` instance that allows the user to select courses to override.

### CODE REVIEW

**Comment by ggoom** [comment]
Overall, functionality is pretty good and smooth!

Some issues and UIUX comments:
- Should "Select Any n" categories (e.g. AUS's) have the Ignore option? Ignoring a class in those sections doesn't really mean anything, so I think it's confusing to have that option there.

- When all classes for a "Select Either" / "Select Any" requirement (e.g. either 6.00 or 6.0001) are Ignored, the cell appearance changes in the "Select Either" menu but not in the main menu. I think it is intuitive that the main menu appearance should update correspondingly.
- I think you do the above for Substitution, but the visual appearance in the main menu is different than other Substitutions, which is confusing:
image

- For categories with "Select Either" requirements, the category's Progress Percentage is buggy:
- The percentage does not appear when the first action in that row is to Ignore a requirement.
- You have to ignore all of the courses in a "Select Either" / "Select Any" category to have it be ignored in the Progress Percentage (this isn't a bug, but is there a way to only have to ignore the requirement once?), and even when the user does this, sometimes it is not ignored in the percentage (but sometimes it is???).

**Comment by venkatesh-sivaraman** [comment]
> * Should "Select Any n" categories (e.g. AUS's) have the Ignore option? Ignoring a class in those sections doesn't really mean anything, so I think it's confusing to have that option there.

I would've thought this is one of the really useful ways in which Ignore can be used - for example, if you're not allowed to count a requirement as an AUS (e.g. because you're counting it for your M.Eng), you can ignore that course and it won't contribute to fulfilling your AUS. That might be difficult to understand though - maybe we should have an alert the first time they choose Ignore that explains how it works?

> * When all classes for a "Select Either" / "Select Any" requirement (e.g. either 6.00 or 6.0001) are Ignored, the cell appearance changes in the "Select Either" menu but not in the main menu. I think it is intuitive that the main menu appearance should update correspondingly.

Good idea - need to ask Richard to do the same thing on Android

> * For categories with "Select Either" requirements, the category's Progress Percentage is buggy:
> * The percentage does not appear when the first action in that row is to Ignore a requirement.

I can't reproduce this - the percentage isn't supposed to appear if it's at 0%. Is that what was happening?

> * You have to ignore all of the courses in a "Select Either" / "Select Any" category to have it be ignored in the Progress Percentage (this isn't a bug, but is there a way to only have to ignore the requirement once?), and even when the user does this, sometimes it is not ignored in the percentage (but sometimes it is???).

I think it's OK to make the user ignore each requirement individually - it's not a good sign if you're marking out whole sections of the requirements :) If it isn't behaving correctly, let me know which major and what courses to put on my road so I can reproduce exactly what you're seeing.

**Comment by sfang22** [comment]
UI has been smooth and very responsive, but I encountered a minor issue with additional requirements where the percentage sign is missing. For additional requirements that want 2 subjects, there isn't a percentage showing for whether the user chooses 1 or 2 or more subjects to replace:
image
image
Meanwhile this what we had in the past:
IMG_1759

**Comment by ggoom** [comment]
> I would've thought this is one of the really useful ways in which Ignore can be used - for example, if you're not allowed to count a requirement as an AUS (e.g. because you're counting it for your M.Eng), you can ignore that course and it won't contribute to fulfilling your AUS. That might be difficult to understand though - maybe we should have an alert the first time they choose Ignore that explains how it works?
Oh right I do remember this, my bad!

> Good idea - need to ask Richard to do the same thing on Android
Cool yeah, this looks better! I wonder if it would make more sense to also overwrite the course number with the words "Substituted" or "Ignored" like you do with other classes.

>I can't reproduce this - the percentage isn't supposed to appear if it's at 0%. Is that what was happening?
Oh my bad, I didn't realize 0% is not supposed to show up.

>I think it's OK to make the user ignore each requirement individually - it's not a good sign if you're marking out whole sections of the requirements :) If it isn't behaving correctly, let me know which major and what courses to put on my road so I can reproduce exactly what you're seeing.
I just realized that this whole time I've been operating under the wrong idea of what Ignore is supposed to do. lol

**Pull request merged**
